#num = int(input("출력할 구구단의 숫자를 입력하라: "))
number =(input("출력할 구구단의 숫자를 입력하라: "))
print(f"{number}단:")
#Print(number + "단:")
#print(number, "단:")
#print(f"{number}단, {number}단, {number}단")
number = int(number)
print = ("number * 2")